# Seata配置
seata:
  application-id: ${spring.application.name}
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: default_tx_group
  # 指定事务分组至集群映射关系，集群名default需要与seata-server注册到Nacos的cluster保持一致
  service:
    vgroup-mapping:
      default_tx_group: default
  config:
    nacos:
      group: SEATA_GROUP
      namespace: seata
      server-addr: 1.15.226.249:8848
      username: nacos
      password: nacos
    type: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      # nacos 服务地址
      server-addr: 1.15.226.249:8848
      namespace: seata
      group: SEATA_GROUP


