server:
  port: 8100
spring:
  application:
    name: springboot-redis-study

#Apollo 配置
app:
  id: SampleApp                            #应用ID
env: DEV
apollo:
  cluster: default                           #指定使用哪个集群的配置
  meta: http://localhost:8080            #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    eagerLoad:
      enabled: true                         #将 Apollo 加载提到初始化日志系统之前
    namespaces: jf-common-test,application                  #设置 Namespace